name: Publish Scientia-Core Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean Dist
        run: rm -rf dist/

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  build-windows:
    needs: build-and-release
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync

      - name: Install PyInstaller
        run: uv pip install pyinstaller

      - name: Build .exe
        run: |
          uv run pyinstaller src/__main__.py \
            --onefile --name scientia-core --console --icon assets/icon.ico \
            --collect-all textual \
            --collect-all markdown_it \
            --collect-all mdit_py_plugins
        shell: bash
        working-directory: ${{ github.workspace }}

      - name: Upload .exe to release
        run: |
          gh release upload ${{ github.event.release.tag_name }} "dist/scientia-core.exe#scientia-core-windows-x86_64.exe" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
